import {retrieve,needsProcedure,procedureQuestion} from './search.js';
const $=s=>document.querySelector(s);let connected=false,token='',lastQuestion='',state={documents:[],cases:[]};
try{state=JSON.parse(localStorage.getItem('spinal-demo'))||state}catch{}
function save(){localStorage.setItem('spinal-demo',JSON.stringify(state))}
function note(t){$('#feedback').textContent=t}
function el(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e}
async function api(action,body={}){const r=await fetch(`/api/service?action=${action}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function message(who,text,sources=[]){const box=el('div',null,`message ${who==='You'?'user':'bot'}`);box.append(el('strong',who),el('p',text));for(const s of sources){const d=el('details');d.append(el('summary',s.title),el('p',s.excerpt));box.append(d)}$('#messages').append(box);$('#messages').scrollTop=$('#messages').scrollHeight}
function show(patient){$('#patient').hidden=!patient;$('#clinician').hidden=patient;$('#patientTab').classList.toggle('selected',patient);$('#clinicianTab').classList.toggle('selected',!patient);note('')}
$('#patientTab').onclick=()=>show(true);$('#clinicianTab').onclick=()=>show(false);
fetch('/api/service?action=status').then(r=>r.json()).then(d=>{connected=d.connected;$('#mode').textContent=connected?'Connected':'Local workspace';if(connected&&!d.email)note('The LLM is connected. Nurse email has not been configured yet.')}).catch(()=>{$('#mode').textContent='Local workspace'});
$('#chatForm').onsubmit=async e=>{e.preventDefault();lastQuestion=$('#question').value.trim();if(!lastQuestion)return;message('You',lastQuestion);$('#question').value='';$('#ask').disabled=true;$('#escalation').hidden=true;note('');try{let d;if(connected)d=await api('chat',{question:lastQuestion});else{const candidates=retrieve(lastQuestion,state.documents);const best=candidates[0];d=needsProcedure(lastQuestion,candidates)?{supported:false,answer:procedureQuestion}:best?{supported:true,answer:'From your approved resource:\n\n'+best.content,sources:[best]}:{supported:false,answer:'I do not have enough information in the approved resources to answer this. You can request a nurse review.'}}message('Spinal Support',d.answer,d.sources);$('#escalation').hidden=d.supported}catch(err){message('Spinal Support',err.message+' No answer has been generated.')}finally{$('#ask').disabled=false}};
$('#escalation').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const body={question:lastQuestion,email:$('#email').value,consent:$('#consent').checked};if(connected){const d=await api('escalate',body);note(d.warning||'Your request was emailed to the nurse team. A clinician will review the reply before it is sent to you.')}else{state.cases.unshift({id:crypto.randomUUID(),question:body.question,email:body.email,status:'awaiting_nurse',draft:''});save();note('Request saved locally. Open the clinician workspace to add a reply. Email delivery is not connected.')}$('#escalation').hidden=true}catch(err){note(err.message)}finally{button.disabled=false}};
async function refresh(){if(connected)state=await api('admin');render()}
$('#login').onsubmit=async e=>{e.preventDefault();token=$('#password').value;try{await refresh();$('#login').hidden=true;$('#workspace').hidden=false;$('#password').value='';note('')}catch(err){token='';note(err.message)}};
$('#logout').onclick=()=>{token='';$('#workspace').hidden=true;$('#login').hidden=false;if(connected)state={documents:[],cases:[]}};
$('#refresh').onclick=()=>refresh().catch(e=>note(e.message));
function render(){renderPending();$('#cases').replaceChildren();if(!state.cases.length)$('#cases').append(el('div','No replies awaiting review.','side-card'));for(const c of state.cases){const card=el('section',null,'case');card.append(el('span',c.status.replaceAll('_',' '),'tag'),el('h3',c.question),el('p','Reply address: '+c.email));
if(!connected&&c.status==='awaiting_nurse'){const label=el('label','Add nurse reply');const draft=el('textarea');draft.rows=4;label.append(draft);const b=el('button','Save nurse draft');b.onclick=()=>{if(!draft.value.trim())return note('Enter a reply');c.draft=draft.value;c.status='review';save();render();note('Draft received. It is not yet sent or added to the resource library.')};card.append(label,b)}
if(['review','delivery_failed'].includes(c.status)){card.append(el('h3','Original nurse reply'),el('pre',c.draft));const label=el('label','Edit the response to send');const answer=el('textarea');answer.rows=5;answer.value=c.approved||c.draft||'';label.append(answer);const checkLabel=el('label',null,'check');const check=el('input');check.type='checkbox';checkLabel.append(check,document.createTextNode('Also add a separately checked, anonymous answer to the resource library'));const reusableLabel=el('label','Reusable general information (remove personal details and quoted email history)');const reusable=el('textarea');reusable.rows=4;reusableLabel.append(reusable);reusableLabel.hidden=true;check.onchange=()=>reusableLabel.hidden=!check.checked;const approve=el('button','Approve and send','primary');approve.onclick=async()=>{if(!answer.value.trim()||(check.checked&&!reusable.value.trim()))return note('Enter the response and, if selected, the anonymous reusable text.');approve.disabled=true;try{if(connected){const d=await api('review',{id:c.id,answer:answer.value,reuse:check.checked,reusable:reusable.value});await refresh();note(d.warning||'Approved response sent.')}else{c.approved=answer.value;c.status='sent';if(check.checked)state.documents.push({id:c.id,title:'Clinician-approved general information',content:reusable.value});save();render();note('Response approved and saved locally. Email delivery is not connected.')}}catch(err){note(err.message);approve.disabled=false}};const reject=el('button','Reject reply');reject.onclick=async()=>{try{if(connected){await api('review',{id:c.id,reject:true});await refresh()}else{c.status='rejected';save();render()}note('Reply rejected; no information was added to the library.')}catch(err){note(err.message)}};card.append(label,checkLabel,reusableLabel,approve,reject)}
if(c.status==='sent')card.append(el('pre',c.approved));if(c.status==='email_failed'&&connected){const b=el('button','Retry nurse email');b.onclick=async()=>{b.disabled=true;try{await api('retry',{id:c.id});await refresh();note('Nurse email sent')}catch(e){note(e.message);b.disabled=false}};card.append(b)}$('#cases').append(card)}$('#documents').replaceChildren();for(const d of state.documents)$('#documents').append(el('div',d.title+' · '+d.content.length.toLocaleString()+' characters','doc'))}
$('#file').onchange=async()=>{const f=$('#file').files[0];if(f){if(f.size>180000)return note('Use a text file under 180 KB');$('#content').value=await f.text();if(!$('#title').value)$('#title').value=f.name}};
$('#documentForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const d={title:$('#title').value.trim(),content:$('#content').value.trim(),id:crypto.randomUUID()};if(connected){await api('document',d);await refresh()}else{state.documents.push(d);save();render()}e.target.reset();note('Resource approved and added. It is now available to the chatbot.')}catch(err){note(err.message)}finally{e.submitter.disabled=false}};
$('#reset').onclick=()=>{if(connected)return note('Only the local workspace can be cleared here');state={documents:[],cases:[]};save();render();note('Local workspace cleared')};

function renderPending(){
 const holder=$('#pendingResources');holder.replaceChildren();const approved=new Set(state.documents.map(x=>x.id));const pending=(window.SPINAL_RESOURCES||[]).filter(x=>!approved.has(x.id));
 if(!pending.length){holder.append(el('p','No resources awaiting review.'));return}
 for(const source of pending){const box=el('details',null,'doc');box.append(el('summary',source.title));box.append(el('p',`${source.content.length.toLocaleString()} characters · PDF pages ${source.firstPage}–${source.lastPage}`));
 const label=el('label','Extracted resource text');const text=el('textarea');text.rows=10;text.value=source.content;label.append(text);const checkLabel=el('label',null,'check');const check=el('input');check.type='checkbox';checkLabel.append(check,document.createTextNode('I have checked this text and approve it for the chatbot.'));
 const button=el('button','Approve resource','primary');button.onclick=async()=>{if(!check.checked)return note('Please confirm that you have reviewed the resource.');if(!text.value.trim())return note('The resource text is empty.');button.disabled=true;try{const doc={id:source.id,title:source.title,content:text.value};if(connected){await api('document',doc);await refresh()}else{state.documents.push(doc);save();render()}note('Resource approved and available to the chatbot.')}catch(e){note(e.message);button.disabled=false}};box.append(label,checkLabel,button);holder.append(box)}
}
