import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import service from '../api/service.js';
const env=process.env;env.ADMIN_TOKEN='test-secret';env.SUPABASE_URL='https://test.supabase.co';env.SUPABASE_SERVICE_ROLE_KEY='test-db';env.GROQ_API_KEY='test-groq';env.RESEND_API_KEY='test-resend';env.NURSE_EMAIL='nurse@example.com';env.EMAIL_FROM='demo@example.com';env.INBOUND_EMAIL='inbound@example.com';env.RESEND_WEBHOOK_SECRET='whsec_'+Buffer.from('secret').toString('base64');
const original=globalThis.fetch;
async function request(action,b={},auth){return service.fetch(new Request('https://site.test/api/service?action='+action,{method:'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},body:JSON.stringify(b)}))}
test('admin denies access without credentials and exposes no database',async()=>{let hit=false;globalThis.fetch=async()=>{hit=true};const r=await request('admin');assert.equal(r.status,401);assert.equal(hit,false);globalThis.fetch=original});
test('empty resources fail closed before calling an LLM',async()=>{globalThis.fetch=async url=>{if(url.endsWith('rpc/check_rate'))return Response.json(true);if(url.includes('/documents?'))return Response.json([]);throw Error('Unexpected provider request')};const r=await request('chat',{question:'What are surgery risks?'});assert.equal((await r.json()).supported,false);globalThis.fetch=original});
test('nurse email failure is saved and honestly reported',async()=>{const writes=[];globalThis.fetch=async(url,opts)=>{if(url.endsWith('rpc/check_rate'))return Response.json(true);if(url.includes('/cases')){writes.push(JSON.parse(opts.body));return Response.json([])}if(url==='https://api.resend.com/emails')return new Response('',{status:500});throw Error('Unexpected request')};const d=await (await request('escalate',{question:'Fictional question',email:'test@example.com',consent:true})).json();assert.ok(d.warning);assert.equal(writes[1].status,'email_failed');globalThis.fetch=original});
test('invalid webhook rejected without retrieval',async()=>{let hit=false;globalThis.fetch=async()=>{hit=true};const r=await request('inbound',{type:'email.received'});assert.equal(r.status,401);assert.equal(hit,false);globalThis.fetch=original});
test('approved reply uses atomic approval before sending',async()=>{const calls=[];const id='11111111-1111-1111-1111-111111111111';globalThis.fetch=async(url,opts)=>{calls.push({url,body:opts?.body?JSON.parse(opts.body):null});if(url.includes('/cases')&&!opts.body)return Response.json([{id,email:'test@example.com',question:'Fictional',status:'review',draft:'Draft'}]);return Response.json([])};const r=await request('review',{id,answer:'Reviewed response',reuse:true,reusable:'Anonymous general information'},env.ADMIN_TOKEN);assert.equal(r.status,200);const atomic=calls.findIndex(c=>c.url.endsWith('rpc/approve_case'));const mail=calls.findIndex(c=>c.url==='https://api.resend.com/emails');assert.ok(atomic>=0&&mail>atomic);assert.equal(calls[atomic].body.reusable_text,'Anonymous general information');globalThis.fetch=original});

test('chat rejects a fabricated quotation even with a valid source number',async()=>{
 globalThis.fetch=async url=>{if(url.endsWith('rpc/check_rate'))return Response.json(true);if(url.includes('/documents?'))return Response.json([{id:'a',title:'Leaflet',content:'Discuss recovery questions with your team.'}]);if(url.includes('groq.com'))return Response.json({choices:[{message:{content:JSON.stringify({supported:true,passages:[{source:1,quote:'Recovery is guaranteed within three days.'}]})}}]});throw Error('Unexpected request')};
 try {const d=await (await request('chat',{question:'recovery questions'})).json();assert.equal(d.supported,false);assert.doesNotMatch(d.answer,/guaranteed/)}finally{globalThis.fetch=original}
});
test('chat renders verified quotations rather than model paraphrases',async()=>{
 globalThis.fetch=async url=>{if(url.endsWith('rpc/check_rate'))return Response.json(true);if(url.includes('/documents?'))return Response.json([{id:'a',title:'Leaflet',content:'Discuss recovery questions with your team.'}]);if(url.includes('groq.com'))return Response.json({choices:[{message:{content:JSON.stringify({supported:true,answer:'Injected unverified answer',passages:[{source:1,quote:'Discuss recovery questions with your team.'}]})}}]});throw Error('Unexpected request')};
 try {const d=await (await request('chat',{question:'recovery questions'})).json();assert.equal(d.supported,true);assert.match(d.answer,/Discuss recovery/);assert.doesNotMatch(d.answer,/Injected/);assert.equal(d.offerReview,true)}finally{globalThis.fetch=original}
});

test('provider failures expose a safe diagnostic reference without raw data',async()=>{
 for(const status of [400,401,429,503]){
 globalThis.fetch=async url=>{if(url.endsWith('rpc/check_rate'))return Response.json(true);if(url.includes('/documents?'))return Response.json([{id:'a',title:'Leaflet',content:'Discuss recovery questions with your team.'}]);if(url.includes('groq.com'))return Response.json({error:{code:status===400?'json_validate_failed':'unknown_private_code',message:'SECRET RAW PAYLOAD'}},{status});throw Error('Unexpected request')};
 try{const d=await (await request('chat',{question:'recovery questions'})).json();assert.match(d.error,new RegExp('HTTP '+status));assert.doesNotMatch(d.error,/SECRET|unknown_private_code/);if(status===400)assert.match(d.error,/json_validate_failed/);if(status===429)assert.match(d.error,/usage limit/)}finally{globalThis.fetch=original}
 }
});
