import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {secureEqual,retrieve,safeModelAnswer,verifyWebhook} from '../lib/core.js';
test('no resources or unrelated resources cannot support an answer',()=>{assert.deepEqual(retrieve('surgery risks',[]),[]);assert.deepEqual(retrieve('surgery risks',[{title:'x',content:'appointment booking'}]),[])});
test('retrieve source excerpt and validate citations',()=>{const c=retrieve('surgery risks',[{id:'1',title:'Leaflet',content:'Discuss surgery risks with your team.'}]);assert.equal(c.length,1);assert.equal(safeModelAnswer({supported:true,answer:'x',sources:[1]},c),true);assert.equal(safeModelAnswer({supported:true,answer:'x',sources:[2]},c),false);assert.equal(safeModelAnswer({supported:true,answer:'x',sources:[]},c),false)});
test('clinician token comparison fails closed',()=>{assert.equal(secureEqual('',undefined),false);assert.equal(secureEqual('abc','abd'),false);assert.equal(secureEqual('abc','abc'),true)});
test('email webhook rejects tampering and stale events',()=>{const raw='{"type":"email.received"}',key=Buffer.from('test signing key'),now=Date.now(),timestamp=String(Math.floor(now/1000)),id='event_1';const h={'svix-id':id,'svix-timestamp':timestamp,'svix-signature':'v1,'+createHmac('sha256',key).update(`${id}.${timestamp}.${raw}`).digest('base64')};const secret='whsec_'+key.toString('base64');assert.equal(verifyWebhook(raw,h,secret,now),true);assert.equal(verifyWebhook(raw+'x',h,secret,now),false);assert.equal(verifyWebhook(raw,h,secret,now+600000),false)});

test('PDF retrieval preserves the matching page reference',()=>{const c=retrieve('appointment questions',[{id:'pdf',title:'Leaflet',content:'[PDF page 1]\nUnrelated title\n[PDF page 2]\nBring appointment questions with you.'}]);assert.equal(c[0].title,'Leaflet · PDF page 2');assert.match(c[0].content,/appointment questions/)});
test('drive retrieves driving rather than generic surgery text',()=>{const c=retrieve('Can I drive after spinal surgery?',[{id:'unrelated',title:'Surgery',content:'Spinal surgery appointment information.'},{id:'correct',title:'Leaflet',content:'Driving after your operation: discuss returning to driving.'}]);assert.equal(c[0].id,'correct');assert.ok(!c.some(x=>x.id==='unrelated'))});
test('general driving question asks for procedure while specific question does not',async()=>{const {needsProcedure}=await import('../search.js');assert.equal(needsProcedure('Can I drive after spinal surgery?',[{}]),true);assert.equal(needsProcedure('Can I drive after single level spinal fixation surgery?',[{}]),false)});
test('single-level driving question excludes multi-level leaflet',()=>{const docs=[{id:'multi',title:'Multi-level Spinal Fixation Surgery Leaflet',content:'Driving surgery driving surgery fixation spinal.'},{id:'single',title:'Single Level Spinal Fixation Surgery Leaflet',content:'Driving after surgery.'}];assert.deepEqual(retrieve('Can I drive after single level spinal fixation surgery?',docs).map(x=>x.id),['single'])});
